export default [
  {label: 'Acquisition Training System', value: 'https://www.epa.gov/privacy/privacy-act-system-records-acquisition-training-system-epa-31'},
  {label: 'Case Application for Debarment and Suspension (CADS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-debarment-and-suspension-files-system-epa-33'},
  {label: 'Central Data Exchange (CDX)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-central-data-exchange-customer-registration-subsystem-epa-52'},
  {label: 'Child Care Tuition Assistance Program Records', value: 'https://www.epa.gov/privacy/privacy-act-system-records-child-care-tuition-assistance-program-records-epa-49'},
  {label: 'Claims Office Master Files', value: 'https://www.epa.gov/privacy/privacy-act-system-records-claims-office-master-files-epa-24'},
  {label: 'Compass', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-travel-other-accounts-payable-and-accounts-receivable-files'},
  {label: 'Continuity of Operations Database (COOP)', value: 'https://www.federalregister.gov/documents/2016/11/03/2016-26487/privacy-act-system-of-records-amendment-of-the-epa-personnel-emergency-contact-files-epa-44'},
  {label: 'Correspondence Management System (CMS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-correspondence-management-system-epa-22'},
  {label: 'eDiscovery', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2012-0882-0001'},
  {label: 'Electronic Physical Access Control System', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-09-17/html/2014-22164.htm'},
  {label: 'Emergency Management Portal - Field Readiness (EMP-FR)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2015-04-16/html/2015-08804.htm'},
  {label: 'Emissions Inspection & Maintenance Records for Federal Employees Parking at Federal Parking Facilities', value: 'https://www.epa.gov/privacy/privacy-act-system-records-emissions-inspection-and-maintenance-records-federal-employees'},
  {label: 'Employee Counseling & Assistance Program Records', value: 'https://www.epa.gov/privacy/privacy-act-system-records-employee-counseling-and-assistance-program-records-epa-27'},
  {label: 'Employment Law Practice Group Case Management System (ELPG-CMS)', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2017-0307-0001'},
  {label: 'Engine and Vehicles Compliance Information System (EV-CIS)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-05-23/html/2014-12019.htm'},
  {label: 'Enterprise Identity and Access Management (EIAM)', value: 'https://www.govinfo.gov/content/pkg/FR-2014-08-19/html/2014-19689.htm'},
  {label: 'Enterprise Legal Case Management System (ELCMS)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-09-17/html/2014-22164.htm'},
  {label: 'Environmental Assessments of Residential Properties (EARP)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2016-04-21/html/2016-09290.htm'},
  {label: 'EPA Identification Card Record', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-identification-card-record-epa-19'},
  {label: 'EPA Personnel Access and Security System (EPASS)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-08-19/html/2014-19689.htm'},
  {label: 'EPA Telecommunication Detail Records', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-telecommunications-detail-records-epa-32'},
  {label: 'Event Brite', value: 'https://www.gpo.gov/fdsys/pkg/FR-2015-08-28/html/2015-21384.htm'},
  {label: 'External Case Tracking System (EXCATS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-external-compliance-program-discrimination-complaint-files-system'},
  {label: 'EZ-Hire', value: 'https://www.epa.gov/privacy/privacy-act-system-records-ezhire-epa-56'},
  {label: 'Federal Docket Management System (FDMS)', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2015-0757-0001'},
  {label: 'Federal Lead-Based Paint Program System of Records (FLPPSOR)', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2017-0588-0001'},
  {label: 'Federal Retirement Benefits Calculator System (FRB)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-federal-retirement-benefits-calculator-epa-55'},
  {label: 'FOIAOnline', value: 'https://www.federalregister.gov/documents/2016/11/17/2016-27669/privacy-act-of-1974-system-of-records'},
  {label: 'HRLOB', value: 'https://www.epa.gov/privacy/privacy-act-system-records-peopleplus-epa-1'},
  {label: 'iCompliants', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2018-0219-0001'},
  {label: 'Inspector General Enterprise Management System (IGEMS) Hotline Module', value: 'https://www.epa.gov/privacy/privacy-act-system-records-inspector-general-enterprise-management-system-hotline-module-epa'},
  {label: 'Inspector General Enterprise Mgmt. System (IGEMS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-inspector-general-enterprise-management-system-audit-assignment'},
  {label: 'Inspector General\'s Enterprise Management (IGEMS) System Investigative Files', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2011-0366-0002'},
  {label: 'Internal User Research and Testing Group', value: 'https://www.govinfo.gov/content/pkg/FR-2014-02-18/html/2014-03431.htm'},
  {label: 'Invention Reports', value: 'https://www.epa.gov/privacy/privacy-act-system-records-invention-reports-submitted-epa-epa-38'},
  {label: 'Labor & Employee Relations Information System (LERIS)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-11-04/html/2014-26175.htm'},
  {label: 'Libby Asbestos Exposure Assessment Records', value: 'https://www.epa.gov/privacy/privacy-act-system-records-libby-asbestos-exposure-assessment-records-epa-48'},
  {label: 'Light Duty In-Use Vehicle Testing Program', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epas-light-duty-use-vehicle-testing-program-information-system'},
  {label: 'MANS', value: 'https://www.federalregister.gov/documents/2016/11/03/2016-26487/privacy-act-system-of-records-amendment-of-the-epa-personnel-emergency-contact-files-epa-44'},
  {label: 'Medical & Research Study of Human Volunteers', value: 'https://www.epa.gov/privacy/privacy-act-system-records-medical-and-research-study-records-human-volunteers-epa-34'},
  {label: 'Medical Surveillance Reasonable Accommodation', value: 'https://www.gpo.gov/fdsys/pkg/FR-2015-04-16/html/2015-08804.htm'},
  {label: 'My Workplace', value: 'https://www.gpo.gov/fdsys/pkg/FR-2014-02-18/html/2014-03431.htm'},
  {label: 'OARM Agency Asset Management System (AAMS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-information-system-office-administrative-services-epa-41'},
  {label: 'Office of Administrative Services Information System (OASIS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-information-system-office-administrative-services-epa-41'},
  {label: 'Office of Compliance NETI eLearning Center', value: 'https://www.epa.gov/privacy/privacy-act-system-records-neti-elearning-center-epa-47'},
  {label: 'OIG Credentials System', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-credential-information-records-epa-23'},
  {label: 'Online Criminal Enforcement Activities Network (OCEAN)', value: 'https://www.federalregister.gov/documents/2006/01/04/06-46/privacy-act-of-1974-republication-of-exempted-system-of-records'},
  {label: 'Passport Expiration Notification System (PENS)', value: 'https://www.federalregister.gov/documents/2016/08/01/2016-18136/privacy-act-system-of-records-establishment-of-new-passport-expiration-notification-system-pens'},
  {label: 'PeoplePlus', value: 'https://www.epa.gov/privacy/privacy-act-system-records-peopleplus-epa-1'},
  {label: 'Personnel Security System (PSS) 2.0', value: 'https://www.regulations.gov/document?D=EPA-HQ-OMS-2019-0371-0001'},
  {label: 'Public Health Emergency Workplace Response System', value: 'https://www.federalregister.gov/documents/2021/06/30/2021-13989/privacy-act-of-1974-system-of-records'},
  {label: 'Reasonable Accommodations Management System (RAMS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-reasonable-accommodations-management-system-epa-73'},
  {label: 'REDCap', value: 'https://www.epa.gov/privacy/privacy-act-system-records-medical-and-research-study-records-human-volunteers-epa-34'},
  {label: 'Region 1 Transit Subsidy System', value: 'https://www.epa.gov/privacy/privacy-act-system-records-information-system-office-administrative-services-epa-41'},
  {label: 'Region 2 Telework', value: 'https://www.epa.gov/privacy/privacy-act-system-records-telework-application-and-agreement-records-epa-61'},
  {label: 'Region 2 Transit Subsidy System', value: 'https://www.epa.gov/privacy/privacy-act-system-records-information-system-office-administrative-services-epa-41'},
  {label: 'Region 3 LAN (GSS) (ECIS)', value: 'https://www.federalregister.gov/documents/2016/11/03/2016-26487/privacy-act-system-of-records-amendment-of-the-epa-personnel-emergency-contact-files-epa-44'},
  {label: 'Regional Inventory and Catalog History (RICH)', value: 'https://www.federalregister.gov/documents/2016/11/03/2016-26487/privacy-act-system-of-records-amendment-of-the-epa-personnel-emergency-contact-files-epa-44'},
  {label: 'Request for Outside Activities', value: 'https://www.oge.gov/Web/oge.nsf/Resources/OGE+GOVT-1'},
  {label: 'Request for Outside Activities', value: 'https://www.oge.gov/Web/oge.nsf/Resources/OGE+GOVT-1'},
  {label: 'Research Grant, Cooperative Agreement & Fellowship Application Files', value: 'https://www.epa.gov/privacy/privacy-act-system-records-research-grant-cooperative-agreement-and-fellowship-application'},
  {label: 'Restricted Use Pesticides (RUPs)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-restricted-use-pesticides-epa-59'},
  {label: 'SAB Contacts', value: 'https://www.epa.gov/privacy/privacy-act-system-records-epa-science-advisory-board-database-scientific-and-technical'},
  {label: 'Section 608', value: 'https://www.regulations.gov/document?D=EPA-HQ-OEI-2017-0205-0001'},
  {label: 'Service Now (SNOW)', value: 'https://www.federalregister.gov/documents/2019/06/11/2019-12300/privacy-act-of-1974-system-of-records'},
  {label: 'Superfund Cost Recovery Package Imaging On-line System (SCORPIOS)', value: 'https://www.epa.gov/privacy/privacy-act-system-records-superfund-cost-recovery-accounting-information-system-epa-39'},
  {label: 'Superfund Enterprise Management (SEMS)', value: 'https://www.gpo.gov/fdsys/pkg/FR-2015-04-17/html/2015-08926.htm'},
  {label: 'Telework', value: 'https://www.epa.gov/privacy/privacy-act-system-records-telework-application-and-agreement-records-epa-61'},
  {label: 'Wellness Program', value: 'https://www.epa.gov/privacy/privacy-act-system-records-wellness-program-medical-records-epa-3'}  
]
